/**
 * AILearningSection Component
 * Section wrapper for AI learning progress display on Profile screen
 *
 * @see Story 7.2: ProgressCircle Component (AI Learning Visualization)
 * @see AC#8: Progress Improvement Notification
 * @see AC#9: Integration with Profile Screen
 */
import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Haptics from 'expo-haptics';

import { ProgressCircle } from '@/components/ui';
import { AILearningModal } from './AILearningModal';
import { useAIProgress } from '@/hooks';
import { colors, spacing } from '@/constants';

// =============================================================================
// Constants
// =============================================================================

/** Storage key for last known progress value */
const LAST_PROGRESS_KEY = 'ai_learning_last_progress';
/** Minimum progress increase to trigger toast (percentage points) */
const PROGRESS_INCREASE_THRESHOLD = 5;

// =============================================================================
// Types
// =============================================================================

export interface AILearningSectionProps {
  /** AI accuracy value from backend (0-1 range) */
  aiAccuracy: number;
  /** Total outfits generated by user */
  totalOutfits: number;
  /** Number of outfits favorited by user */
  favoriteCount: number;
  /** Callback when progress improvement should trigger toast (AC#8) */
  onProgressImprovement?: () => void;
}

// =============================================================================
// Component
// =============================================================================

/**
 * AILearningSection - AI learning progress section
 *
 * Features:
 * - Section title "AI 学习进度"
 * - ProgressCircle with animated progress
 * - Dynamic stage message
 * - Tap to open tips modal
 * - Celebratory toast when progress improves >= 5%
 */
export function AILearningSection({
  aiAccuracy,
  totalOutfits,
  favoriteCount,
  onProgressImprovement,
}: AILearningSectionProps): React.ReactElement {
  const [isModalVisible, setModalVisible] = useState(false);

  // Track if toast has been shown this session (only show once per session)
  const hasShownToastThisSession = useRef(false);
  // Track if component is mounted for cleanup
  const isMounted = useRef(true);

  // Calculate progress and stage message
  const { progress, stageMessage } = useAIProgress({
    aiAccuracy,
    totalOutfits,
    favoriteCount,
  });

  // Check for progress improvement and notify parent (AC#8)
  useEffect(() => {
    isMounted.current = true;

    const checkProgressImprovement = async () => {
      // Skip if toast already shown this session
      if (hasShownToastThisSession.current) {
        return;
      }

      try {
        const lastProgressStr = await AsyncStorage.getItem(LAST_PROGRESS_KEY);
        const lastProgress = lastProgressStr ? parseInt(lastProgressStr, 10) : 0;

        // Check if progress increased by >= 5%
        if (progress - lastProgress >= PROGRESS_INCREASE_THRESHOLD) {
          // Only update state if still mounted
          if (isMounted.current) {
            hasShownToastThisSession.current = true;

            // Trigger success haptic feedback
            await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);

            // Notify parent to show toast
            onProgressImprovement?.();
          }
        }

        // Save current progress for next comparison
        await AsyncStorage.setItem(LAST_PROGRESS_KEY, progress.toString());
      } catch (error) {
        // Silently handle storage errors
        if (__DEV__) {
          console.warn('[AILearningSection] Error checking progress:', error);
        }
      }
    };

    // Only check when progress > 0 (data loaded)
    if (progress > 0) {
      checkProgressImprovement();
    }

    // Cleanup function
    return () => {
      isMounted.current = false;
    };
  }, [progress, onProgressImprovement]);

  // Handle progress circle press - open modal
  const handleProgressPress = () => {
    setModalVisible(true);
  };

  // Handle modal close
  const handleModalClose = () => {
    setModalVisible(false);
  };

  return (
    <View style={styles.container}>
      {/* Section title */}
      <Text style={styles.sectionTitle}>AI 学习进度</Text>

      {/* Progress circle */}
      <View style={styles.progressContainer}>
        <ProgressCircle
          progress={progress}
          size={160}
          strokeWidth={12}
          label={stageMessage}
          onPress={handleProgressPress}
        />
      </View>

      {/* Tips modal */}
      <AILearningModal
        visible={isModalVisible}
        onClose={handleModalClose}
      />
    </View>
  );
}

// =============================================================================
// Styles
// =============================================================================

const styles = StyleSheet.create({
  container: {
    marginBottom: spacing.l,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.gray1,
    marginBottom: spacing.m,
  },
  progressContainer: {
    alignItems: 'center',
    marginVertical: spacing.m,
  },
});

export default AILearningSection;
