"""Add outfit and share_record tables and user profile fields

Revision ID: 3e390cb5626f
Revises: 97db65a6eeb6
Create Date: 2026-01-13 16:54:20.495450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e390cb5626f'
down_revision: Union[str, Sequence[str], None] = '97db65a6eeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('share_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outfit_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('template_style', sa.String(length=50), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_records_user_id'), 'share_records', ['user_id'], unique=False)
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'nickname')
    op.drop_index(op.f('ix_share_records_user_id'), table_name='share_records')
    op.drop_table('share_records')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_table('outfits')
    # ### end Alembic commands ###
