/**
 * useAIProgress Hook
 * Calculates AI learning progress and stage message based on user activity
 *
 * @see Story 7.2: ProgressCircle Component (AI Learning Visualization)
 * @see AC#5: AI Learning Progress Calculation
 * @see AC#6: Dynamic Progress Stage Messages
 */
import { useMemo } from 'react';

// =============================================================================
// Types
// =============================================================================

export interface UseAIProgressParams {
  /** AI accuracy value from backend (0-1 range) */
  aiAccuracy: number;
  /** Total outfits generated by user */
  totalOutfits: number;
  /** Number of outfits favorited by user */
  favoriteCount: number;
}

export interface UseAIProgressResult {
  /** Progress percentage (0-100) */
  progress: number;
  /** Stage message based on progress level */
  stageMessage: string;
}

// =============================================================================
// Constants
// =============================================================================

/** Progress formula weights */
const OUTFIT_WEIGHT = 30;
const FAVORITE_WEIGHT = 40;
const ACCEPT_RATE_WEIGHT = 30;

/** Thresholds for score calculation */
const OUTFIT_THRESHOLD = 20;
const FAVORITE_THRESHOLD = 10;

/** Stage message thresholds and messages */
const STAGE_MESSAGES = {
  STAGE_1: { max: 20, message: 'AI 正在学习你的风格...' },
  STAGE_2: { max: 50, message: 'AI 开始了解你的喜好了' },
  STAGE_3: { max: 80, message: 'AI 越来越懂你啦' },
  STAGE_4: { max: 100, message: 'AI 已经很懂你的风格了！' },
} as const;

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Calculate progress score from individual components
 * Formula from AC#5:
 * progress = min(100,
 *   (outfitCount / 20) * 30 +
 *   (likeCount / 10) * 40 +
 *   (acceptRate * 100) * 30
 * )
 */
function calculateFallbackProgress(
  totalOutfits: number,
  favoriteCount: number,
  aiAccuracy: number
): number {
  const outfitScore = Math.min(OUTFIT_WEIGHT, (totalOutfits / OUTFIT_THRESHOLD) * OUTFIT_WEIGHT);
  const favoriteScore = Math.min(FAVORITE_WEIGHT, (favoriteCount / FAVORITE_THRESHOLD) * FAVORITE_WEIGHT);
  const acceptRateScore = Math.min(ACCEPT_RATE_WEIGHT, Math.max(0, aiAccuracy) * ACCEPT_RATE_WEIGHT);

  return Math.min(100, Math.round(outfitScore + favoriteScore + acceptRateScore));
}

/**
 * Get stage message based on progress percentage
 */
function getStageMessage(progress: number): string {
  if (progress <= STAGE_MESSAGES.STAGE_1.max) {
    return STAGE_MESSAGES.STAGE_1.message;
  } else if (progress <= STAGE_MESSAGES.STAGE_2.max) {
    return STAGE_MESSAGES.STAGE_2.message;
  } else if (progress <= STAGE_MESSAGES.STAGE_3.max) {
    return STAGE_MESSAGES.STAGE_3.message;
  } else {
    return STAGE_MESSAGES.STAGE_4.message;
  }
}

// =============================================================================
// Hook
// =============================================================================

/**
 * Calculate AI learning progress and stage message
 *
 * Uses backend-provided aiAccuracy when available (> 0),
 * otherwise calculates fallback from totalOutfits and favoriteCount.
 *
 * @param params - User activity data for progress calculation
 * @returns Progress percentage (0-100) and stage message
 */
export function useAIProgress({
  aiAccuracy,
  totalOutfits,
  favoriteCount,
}: UseAIProgressParams): UseAIProgressResult {
  const progress = useMemo(() => {
    // Use backend aiAccuracy directly if valid (> 0)
    if (aiAccuracy > 0) {
      return Math.min(100, Math.round(aiAccuracy * 100));
    }

    // Fallback: calculate from available data
    return calculateFallbackProgress(totalOutfits, favoriteCount, aiAccuracy);
  }, [aiAccuracy, totalOutfits, favoriteCount]);

  const stageMessage = useMemo(() => {
    return getStageMessage(progress);
  }, [progress]);

  return { progress, stageMessage };
}

export default useAIProgress;
